version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
