version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog 
    volumes:
      - ./backend:/app
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    env_file:
      - ./frontend/.env.local
    environment:
    - NEXT_PUBLIC_API_URL=http://192.168.100.5:8000     
    - SERVER_API_URL=http://backend:8000       
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  
      - "8025:8025"  
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge