"""add image_url to lots

Revision ID: 8f7fbc1873cf
Revises: 6bbfda2c9a42
Create Date: 2025-07-26 12:26:34.291141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7fbc1873cf'
down_revision: Union[str, Sequence[str], None] = '6bbfda2c9a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'image_url')
    # ### end Alembic commands ###
