"""Add full Lot fields

Revision ID: cea0f5ab46b9
Revises: 3e92687efefa
Create Date: 2025-07-24 16:42:07.269347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea0f5ab46b9'
down_revision: Union[str, Sequence[str], None] = '3e92687efefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('lots', sa.Column('start_price', sa.Float(), nullable=True))
    op.add_column('lots', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('lots', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('lot_materials', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('auction_name', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('author', sa.String(), nullable=True))
    op.create_foreign_key(None, 'lots', 'users', ['owner_id'], ['id'])
    op.drop_column('lots', 'price_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('price_start', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lots', type_='foreignkey')
    op.drop_column('lots', 'author')
    op.drop_column('lots', 'auction_name')
    op.drop_column('lots', 'lot_materials')
    op.drop_column('lots', 'owner_id')
    op.drop_column('lots', 'start_time')
    op.drop_column('lots', 'start_price')
    op.drop_column('lots', 'current_price')
    # ### end Alembic commands ###
